In [23]:
from sklearn import datasets
from sklearn.preprocessing import LabelBinarizer
import numpy as np

In [24]:
data = datasets.load_breast_cancer()

In [25]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [26]:
features = data.data
y = data.target

In [27]:
ys = LabelBinarizer().fit_transform(y)
n = features.shape[0]

In [28]:
self.n_train = 10
self.n_val = 10
self.n_es = 10


In [33]:
from sklearn.model_selection import train_test_split

In [32]:
train, test, y_train, y_test = train_test_split(np.arange(n), y, random_state=self.seed,
                                                train_size=self.n_train + self.n_val + self.n_es,
                                                test_size=n - self.n_train - self.n_val - self.n_es,
                                                stratify=y)
train, es, y_train, y_es = train_test_split(train, y_train, random_state=self.seed,
                                            train_size=self.n_train + self.n_val, test_size=self.n_es,
                                            stratify=y_train)
train, val, y_train, y_val = train_test_split(train, y_train, random_state=self.seed,
                                                train_size=self.n_train, test_size=self.n_val,
                                                stratify=y_train)

train_mask = np.zeros([n, ], dtype=bool)
train_mask[train] = True
val_mask = np.zeros([n, ], dtype=bool)
val_mask[val] = True
es_mask = np.zeros([n, ], dtype=bool)
es_mask[es] = True
test_mask = np.zeros([n, ], dtype=bool)
test_mask[test] = True

(569, 2)

In [12]:
import tensorflow as tf
import numpy as np

In [71]:
labels = tf.constant([[1.,2.,5.],[6.,0.,0.],[3.,3.,3.]], name='labels')
preds = tf.constant([[0.,0.,0.],[0.,0.,0.],[0.,0.,0.]], name='preds')
label_mask = tf.placeholder(tf.int32)
label_mask = tf.cast(label_mask, tf.float32)

num_test = tf.reduce_sum(label_mask)
error = tf.squared_difference(tf.transpose(preds)*label_mask, tf.transpose(labels)*label_mask)
error2 = tf.reduce_sum(error)/(tf.cast(num_test, tf.float32)*tf.cast(labels.shape[0],tf.float32))

mask = np.array([True,True,False])
with tf.Session() as sess:
    error = sess.run(fetches=error, feed_dict={label_mask:mask})
    error2 = sess.run(fetches=error2, feed_dict={label_mask:mask})

print(error)
print(error2)
print('h')

[[ 1. 36.  0.]
 [ 4.  0.  0.]
 [25.  0.  0.]]
11.0
h


2022-05-16 16:20:25.460635: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: NVIDIA Quadro GP100 major: 6 minor: 0 memoryClockRate(GHz): 1.4425
pciBusID: 0000:b3:00.0
2022-05-16 16:20:25.460721: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
2022-05-16 16:20:25.460732: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10
2022-05-16 16:20:25.460741: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10
2022-05-16 16:20:25.460749: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10
2022-05-16 16:20:25.460758: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10
2022-05-16 16:20:25.460766: I tensorflow/stream_executor/platfo